CREATE external TABLE `nestedblog.json_store_sales_streaming` ( 

`ss_addr_sk` BIGINT,
`ss_cdemo_sk` BIGINT,
`ss_coupon_amt` DOUBLE,
`ss_customer` STRUCT<`c_birth_country`: STRING, `c_birth_day`: BIGINT, `c_birth_month`: BIGINT, `c_birth_year`: BIGINT, `c_current_addr_sk`: BIGINT,
    `c_current_address`: STRUCT<`ca_address_id`: STRING, `ca_city`: STRING, `ca_country`: STRING, `ca_county`: STRING, `ca_gmt_offset`: DOUBLE, `ca_location_type`: STRING, `ca_state`: STRING, `ca_street_name`: STRING, `ca_street_number`: STRING, `ca_street_type`: STRING, `ca_suite_number`: STRING, `ca_zip`: STRING>, `c_current_cdemo_sk`: BIGINT, 
    `c_current_customer_demographics`: STRUCT<`cd_credit_rating`: STRING, `cd_dep_college_count`: BIGINT, `cd_dep_count`: BIGINT, `cd_dep_employed_count`: BIGINT, `cd_education_status`: STRING, `cd_gender`: STRING, `cd_marital_status`: STRING, `cd_purchase_estimate`: BIGINT>, `c_current_hdemo_sk`: BIGINT, 
    `c_current_household_demographics`: STRUCT<`hd_buy_potential`: STRING, `hd_dep_count`: BIGINT, 
        `hd_income_band`: STRUCT<`ib_lower_bound`: BIGINT, `ib_upper_bound`: BIGINT>, `hd_income_band_sk`: BIGINT, `hd_income_band_sk_row_num`: BIGINT, `hd_vehicle_count`: BIGINT>, `c_customer_id`: STRING, `c_email_address`: STRING, `c_first_name`: STRING, 
        `c_first_sales_date`: STRUCT<`d_current_day`: STRING, `d_current_month`: STRING, `d_current_quarter`: STRING, `d_current_week`: STRING, `d_current_year`: STRING, `d_date`: STRING, `d_date_id`: STRING, `d_day_name`: STRING, `d_dom`: BIGINT, `d_dow`: BIGINT, `d_first_dom`: BIGINT, `d_following_holiday`: STRING, `d_fy_quarter_seq`: BIGINT, `d_fy_week_seq`: BIGINT, `d_fy_year`: BIGINT, `d_holiday`: STRING, `d_last_dom`: BIGINT, `d_month_seq`: BIGINT, `d_moy`: BIGINT, `d_qoy`: BIGINT, `d_quarter_name`: STRING, `d_quarter_seq`: BIGINT, `d_same_day_lq`: BIGINT, `d_same_day_ly`: BIGINT, `d_week_seq`: BIGINT, `d_weekend`: STRING, `d_year`: BIGINT>, `c_first_sales_date_sk`: BIGINT, 
        `c_first_shipto_date`: STRUCT<`d_current_day`: STRING, `d_current_month`: STRING, `d_current_quarter`: STRING, `d_current_week`: STRING, `d_current_year`: STRING, `d_date`: STRING, `d_date_id`: STRING, `d_day_name`: STRING, `d_dom`: BIGINT, `d_dow`: BIGINT, `d_first_dom`: BIGINT, `d_following_holiday`: STRING, `d_fy_quarter_seq`: BIGINT, `d_fy_week_seq`: BIGINT, `d_fy_year`: BIGINT, `d_holiday`: STRING, `d_last_dom`: BIGINT, `d_month_seq`: BIGINT, `d_moy`: BIGINT, `d_qoy`: BIGINT, `d_quarter_name`: STRING, `d_quarter_seq`: BIGINT, `d_same_day_lq`: BIGINT, `d_same_day_ly`: BIGINT, `d_week_seq`: BIGINT, `d_weekend`: STRING, `d_year`: BIGINT>, `c_first_shipto_date_sk`: BIGINT, `c_last_name`: STRING, 
        `c_last_review_date`: STRUCT<`d_current_day`: STRING, `d_current_month`: STRING, `d_current_quarter`: STRING, `d_current_week`: STRING, `d_current_year`: STRING, `d_date`: STRING, `d_date_id`: STRING, `d_day_name`: STRING, `d_dom`: BIGINT, `d_dow`: BIGINT, `d_first_dom`: BIGINT, `d_following_holiday`: STRING, `d_fy_quarter_seq`: BIGINT, `d_fy_week_seq`: BIGINT, `d_fy_year`: BIGINT, `d_holiday`: STRING, `d_last_dom`: BIGINT, `d_month_seq`: BIGINT, `d_moy`: BIGINT, `d_qoy`: BIGINT, `d_quarter_name`: STRING, `d_quarter_seq`: BIGINT, `d_same_day_lq`: BIGINT, `d_same_day_ly`: BIGINT, `d_week_seq`: BIGINT, `d_weekend`: STRING, `d_year`: BIGINT>, `c_last_review_date_sk`: BIGINT, `c_preferred_cust_flag`: STRING, `c_salutation`: STRING>,
`ss_customer_address` STRUCT<`ca_address_id`: STRING, `ca_city`: STRING, `ca_country`: STRING, `ca_county`: STRING, `ca_gmt_offset`: DOUBLE, `ca_location_type`: STRING, `ca_state`: STRING, `ca_street_name`: STRING, `ca_street_number`: STRING, `ca_street_type`: STRING, `ca_suite_number`: STRING, `ca_zip`: STRING>,
`ss_customer_demographics` STRUCT<`cd_credit_rating`: STRING, `cd_dep_college_count`: BIGINT, `cd_dep_count`: BIGINT, `cd_dep_employed_count`: BIGINT, `cd_education_status`: STRING, `cd_gender`: STRING, `cd_marital_status`: STRING, `cd_purchase_estimate`: BIGINT>,`ss_customer_sk` BIGINT,
`ss_date_dim` STRUCT<`d_current_day`: STRING, `d_current_month`: STRING, `d_current_quarter`: STRING, `d_current_week`: STRING, `d_current_year`: STRING, `d_date`: STRING, `d_date_id`: STRING, `d_day_name`: STRING, `d_dom`: BIGINT, `d_dow`: BIGINT, `d_first_dom`: BIGINT, `d_following_holiday`: STRING, `d_fy_quarter_seq`: BIGINT, `d_fy_week_seq`: BIGINT, `d_fy_year`: BIGINT, `d_holiday`: STRING, `d_last_dom`: BIGINT, `d_month_seq`: BIGINT, `d_moy`: BIGINT, `d_qoy`: BIGINT, `d_quarter_name`: STRING, `d_quarter_seq`: BIGINT, `d_same_day_lq`: BIGINT, `d_same_day_ly`: BIGINT, `d_week_seq`: BIGINT, `d_weekend`: STRING, `d_year`: BIGINT>,`ss_ext_discount_amt` DOUBLE,`ss_ext_list_price` DOUBLE,`ss_ext_sales_price` DOUBLE,`ss_ext_tax` DOUBLE,`ss_ext_wholesale_cost` DOUBLE,`ss_hdemo_sk` BIGINT,
`ss_household_demographics` STRUCT<`hd_buy_potential`: STRING, `hd_dep_count`: BIGINT, 
    `hd_income_band`: STRUCT<`ib_lower_bound`: BIGINT, `ib_upper_bound`: BIGINT>, `hd_income_band_sk`: BIGINT, `hd_vehicle_count`: BIGINT>,
`ss_item` STRUCT<`i_brand`: STRING, `i_brand_id`: BIGINT, `i_category`: STRING, `i_category_id`: BIGINT, `i_class`: STRING, `i_class_id`: BIGINT, `i_color`: STRING, `i_container`: STRING, `i_current_price`: DOUBLE, `i_formulation`: STRING, `i_item_desc`: STRING, `i_item_id`: STRING, `i_manager_id`: BIGINT, `i_manufact`: STRING, `i_manufact_id`: BIGINT, `i_product_name`: STRING, `i_rec_end_date`: STRING, `i_rec_start_date`: STRING, `i_size`: STRING, `i_units`: STRING, `i_wholesale_cost`: DOUBLE>,`ss_item_sk` BIGINT,`ss_list_price` DOUBLE,`ss_net_paid` DOUBLE,`ss_net_paid_inc_tax` DOUBLE,`ss_net_profit` DOUBLE,`ss_promo_sk` BIGINT,
`ss_promotion` STRUCT<`p_channel_catalog`: STRING, `p_channel_demo`: STRING, `p_channel_details`: STRING, `p_channel_dmail`: STRING, `p_channel_email`: STRING, `p_channel_event`: STRING, `p_channel_press`: STRING, `p_channel_radio`: STRING, `p_channel_tv`: STRING, `p_cost`: DOUBLE, `p_discount_active`: STRING,
    `p_end_date`: STRUCT<`d_current_day`: STRING, `d_current_month`: STRING, `d_current_quarter`: STRING, `d_current_week`: STRING, `d_current_year`: STRING, `d_date`: STRING, `d_date_id`: STRING, `d_day_name`: STRING, `d_dom`: BIGINT, `d_dow`: BIGINT, `d_first_dom`: BIGINT, `d_following_holiday`: STRING, `d_fy_quarter_seq`: BIGINT, `d_fy_week_seq`: BIGINT, `d_fy_year`: BIGINT, `d_holiday`: STRING, `d_last_dom`: BIGINT, `d_month_seq`: BIGINT, `d_moy`: BIGINT, `d_qoy`: BIGINT, `d_quarter_name`: STRING, `d_quarter_seq`: BIGINT, `d_same_day_lq`: BIGINT, `d_same_day_ly`: BIGINT, `d_week_seq`: BIGINT, `d_weekend`: STRING, `d_year`: BIGINT>, `p_end_date_sk`: BIGINT, 
    `p_item`: STRUCT<`i_brand`: STRING, `i_brand_id`: BIGINT, `i_category`: STRING, `i_category_id`: BIGINT, `i_class`: STRING, `i_class_id`: BIGINT, `i_color`: STRING, `i_container`: STRING, `i_current_price`: DOUBLE, `i_formulation`: STRING, `i_item_desc`: STRING, `i_item_id`: STRING, `i_manager_id`: BIGINT, `i_manufact`: STRING, `i_manufact_id`: BIGINT, `i_product_name`: STRING, `i_rec_end_date`: STRING, `i_rec_start_date`: STRING, `i_size`: STRING, `i_units`: STRING, `i_wholesale_cost`: DOUBLE>, `p_item_sk`: BIGINT, `p_promo_id`: STRING, `p_promo_name`: STRING, `p_purpose`: STRING, `p_response_target`: BIGINT, 
    `p_start_date`: STRUCT<`d_current_day`: STRING, `d_current_month`: STRING, `d_current_quarter`: STRING, `d_current_week`: STRING, `d_current_year`: STRING, `d_date`: STRING, `d_date_id`: STRING, `d_day_name`: STRING, `d_dom`: BIGINT, `d_dow`: BIGINT, `d_first_dom`: BIGINT, `d_following_holiday`: STRING, `d_fy_quarter_seq`: BIGINT, `d_fy_week_seq`: BIGINT, `d_fy_year`: BIGINT, `d_holiday`: STRING, `d_last_dom`: BIGINT, `d_month_seq`: BIGINT, `d_moy`: BIGINT, `d_qoy`: BIGINT, `d_quarter_name`: STRING, `d_quarter_seq`: BIGINT, `d_same_day_lq`: BIGINT, `d_same_day_ly`: BIGINT, `d_week_seq`: BIGINT, `d_weekend`: STRING, `d_year`: BIGINT>, `p_start_date_sk`: BIGINT>,`ss_quantity` BIGINT,`ss_sales_price` DOUBLE,`ss_sold_time_sk` BIGINT,
`ss_store` STRUCT<`s_city`: STRING, 
    `s_closed_date`: STRUCT<`d_current_day`: STRING, `d_current_month`: STRING, `d_current_quarter`: STRING, `d_current_week`: STRING, `d_current_year`: STRING, `d_date`: STRING, `d_date_id`: STRING, `d_day_name`: STRING, `d_dom`: BIGINT, `d_dow`: BIGINT, `d_first_dom`: BIGINT, `d_following_holiday`: STRING, `d_fy_quarter_seq`: BIGINT, `d_fy_week_seq`: BIGINT, `d_fy_year`: BIGINT, `d_holiday`: STRING, `d_last_dom`: BIGINT, `d_month_seq`: BIGINT, `d_moy`: BIGINT, `d_qoy`: BIGINT, `d_quarter_name`: STRING, `d_quarter_seq`: BIGINT, `d_same_day_lq`: BIGINT, `d_same_day_ly`: BIGINT, `d_week_seq`: BIGINT, `d_weekend`: STRING, `d_year`: BIGINT>, `s_closed_date_sk`: BIGINT, `s_company_id`: BIGINT, `s_company_name`: STRING, `s_country`: STRING, `s_county`: STRING, `s_division_id`: BIGINT, `s_division_name`: STRING, `s_floor_space`: BIGINT, `s_geography_class`: STRING, `s_gmt_offset`: DOUBLE, `s_hours`: STRING, `s_manager`: STRING, `s_market_desc`: STRING, `s_market_id`: BIGINT, `s_market_manager`: STRING, `s_number_employees`: BIGINT, `s_rec_end_date`: STRING, `s_rec_start_date`: STRING, `s_state`: STRING, `s_store_id`: STRING, `s_store_name`: STRING, `s_street_name`: STRING, `s_street_number`: STRING, `s_street_type`: STRING, `s_suite_number`: STRING, `s_tax_precentage`: DOUBLE, `s_zip`: STRING>,`ss_store_sk` BIGINT,`ss_ticket_number` BIGINT,
    `ss_time_dim` STRUCT<`t_am_pm`: STRING, `t_hour`: BIGINT, `t_meal_time`: STRING, `t_minute`: BIGINT, `t_second`: BIGINT, `t_shift`: STRING, `t_sub_shift`: STRING, `t_time`: BIGINT, `t_time_id`: STRING>,`ss_wholesale_cost` DOUBLE
)
PARTITIONED BY (year int, month int, day int) 
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe' LOCATION 's3://jwyant-nestedblog/tpcds/streaming/store_sales/'
---------------
MSCK REPAIR TABLE json_store_sales_streaming
select * from json_store_sales_streaming limit 100